version: '3.8'

services:
  db:
    image: mariadb:${MARIADB_VERSION:-latest}
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ${PROJECT_SQLDUMB}:/docker-entrypoint-initdb.d/schema.sql:ro
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MARIADB_DATABASE: "${DB_NAME}"
      MARIADB_USER: "${DB_USERNAME}"
      MARIADB_PASSWORD: "${DB_PASSWORD}"
    container_name: db
    command: --log-bin --binlog-format=MIXED

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    restart: always
    networks:
      - frontend
      - backend
    environment:
      PMA_HOST: db
    depends_on:
      - db

networks:
  frontend:
  backend: